[package]
name = "temporal_input_buffer"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0.214", features = ["derive"] }
bincode = { version = "2.0", default-features = false, features = [
  "std",
  "serde",
] }

[dev-dependencies]
test-case = "3.3.1"
