name: Rust CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Install Rust toolchain (nightly) via the rust-lang setup action
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: nightly

      - name: Build
        run: cargo build

      - name: Test
        run: cargo test

  coverage:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: nightly
          components: llvm-tools-preview

      - uses: taiki-e/install-action@v2
        with:
          tool: cargo-llvm-cov

      - name: Prepare coverage output directories
        run: |
          mkdir -p target/llvm-cov
          mkdir -p target/llvm-cov/html

      - name: Collect LCOV coverage report
        run: >-
          cargo llvm-cov --branch --workspace --all-targets --lcov
          --output-path target/llvm-cov/lcov.info

      - name: Generate HTML coverage report
        run: >-
          cargo llvm-cov report --branch --html --output-dir
          target/llvm-cov/html

      - name: Upload coverage HTML report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-html
          path: target/llvm-cov/html/

      - name: Upload coverage LCOV report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-lcov
          path: target/llvm-cov/lcov.info